Fix: add BindingResult param to api interface template for spring mvc
Backbase/backbase-openapi-tools pull request #193
Opened 2021-04-01 10:15 UTC by sophiejanssens

Added BindingResult method parameter in the interface method for Spring codegen, only used if @valid is used.

2021-04-06 16:17 UTC, pa314159 approved these changes

2021-04-08 08:34 UTC, pa314159 requested changes
It would be nice to add a test for this new parameter

2021-04-08 08:34 UTC, pa314159 commented on boat-scaffold/src/main/templates/boat-spring/bodyParams.mustache
> +            @RequestBody{{^required}}(required = false){{/required}} {{^reactive}}{{{dataType}}}{{/reactive}}{{#reactive}}{{^isListContainer}}Mono{{/isListContainer}}{{#isListContainer}}Flux{{/isList
There is an extra space before your changes that is not needed

2021-04-08 08:41 UTC, pa314159 commented
Please also update README.md
- the Release Notes section
- the list of the Configuration options at the bottom

2021-04-09 12:03 UTC, bbzurek commented on boat-scaffold/src/main/templates/boat-spring/api.mustache
> +import org.springframework.validation.BindingResult
missing `;`

2021-04-13 13:21 UTC, christopherm-backbase approved these changes

2021-04-13 13:21 UTC, christopherm-backbase commented on README.md
> +| `addBindingResult` | Adds BindingResult to Api method definitions' request bodies, if UseBeanValidation configured, for this to be effective use configuration UseBeanValidation (Default: false)|
Does addBindingResult also enable useBeanValidation? The description here is a bit awkward.

2021-04-13 19:04 UTC, pa314159 approved these changes

2021-04-13 19:07 UTC, merged