Added JSDoc comments to all overloads of operation functions in typescript client
Backbase/backbase-openapi-tools pull request #217
Opened 2021-08-05 11:29 UTC by daiscog

Fixes #216

2021-08-05 14:11 UTC, bartveenstra requested changes
Looks great! Can you add some release notes as well in the reame.md?

2021-08-05 16:12 UTC, thor84no approved these changes

2021-08-06 07:37 UTC, santam85 approved these changes

2021-08-06 08:13 UTC, daiscog commented
@bartveenstra I've updated the readme.  Happy for me to merge?

2021-08-06 17:01 UTC, merged